'use client'
import { useEffect, useState } from 'react'

export default function B2BGame() {
  const [punchline, setPunchline] = useState(null)
  const [hasAnswered, setHasAnswered] = useState(false)
  const [userAnswer, setUserAnswer] = useState(null)

  const fetchPunchline = async () => {
    const res = await fetch('/api/b2b-random')
    const data = await res.json()
    setPunchline(data)
    setHasAnswered(false)
    setUserAnswer(null)
  }

  useEffect(() => {
    fetchPunchline()
  }, [])

  const handleAnswer = (isTrue) => {
    setUserAnswer(isTrue)
    setHasAnswered(true)
  }

  return (
    <main className="min-h-screen bg-black text-white flex flex-col items-center justify-center px-4 py-12">
      <h1 className="text-3xl font-bold text-red-500 mb-8">🔥 Bendo na Bendo</h1>

      {punchline ? (
        <>
          <div className="bg-gray-900 text-white text-center rounded-lg p-6 shadow-lg max-w-2xl break-words">
          <p className="text-xl md:text-2xl font-semibold mb-4 whitespace-pre-wrap break-words">
            {punchline.text || '🤔 No punchline found.'}
            </p>
          </div>

          {!hasAnswered ? (
            <>
              <p className="text-sm text-gray-400 mt-6 mb-4">
                🧠 Is this a real French rap punchline or was it generated by an AI?
              </p>
              <div className="flex gap-6">
                <button
                  onClick={() => handleAnswer(true)}
                  className="bg-green-600 hover:bg-green-700 px-6 py-3 rounded text-lg font-bold"
                >
                  TRUE
                </button>
                <button
                  onClick={() => handleAnswer(false)}
                  className="bg-red-600 hover:bg-red-700 px-6 py-3 rounded text-lg font-bold"
                >
                  FALSE
                </button>
              </div>
            </>
          ) : (
            <>
              <p className="mt-6 text-lg text-center">
                {userAnswer === punchline.isReal ? '✅ Correct!' : '❌ Wrong!'}
              </p>

              {punchline.isReal ? (
                <p className="mt-2 text-center text-sm text-gray-400">
                  This punchline is real.  
                  <br />
                  🎤 <strong>{punchline.artist} – {punchline.title}</strong>  
                  <br />
                  <span className="text-gray-500 italic">(Source: {punchline.source})</span>
                </p>
              ) : (
                <p className="mt-2 text-center text-sm text-gray-400">
                  🤖 This was generated by an AI.
                </p>
              )}

              <button
                onClick={fetchPunchline}
                className="mt-6 bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded text-sm font-semibold"
              >
                Next punchline 🔁
              </button>
            </>
          )}
        </>
      ) : (
        <p className="text-gray-400">Loading punchline...</p>
      )}
    </main>
  )
}
