// Rewrite dead Supabase URLs to Vercel Blob URLs in whatever DB DATABASE_URL points to.
// Reads url map from scripts/_url-map.json (generated by migrate-storage.mjs).
//
// Usage:
//   node --env-file=.env.production scripts/rewrite-urls.mjs

import { readFileSync } from 'node:fs'
import { neon } from '@neondatabase/serverless'

const urlMap = JSON.parse(readFileSync('scripts/_url-map.json', 'utf8'))
const sql = neon(process.env.DATABASE_URL)

console.log(`Rewriting URLs in DB: ${process.env.DATABASE_URL.split('@')[1].split('/')[0]}`)
console.log(`Replacements to attempt: ${Object.keys(urlMap).length}`)

let totalRows = 0
for (const [oldUrl, newUrl] of Object.entries(urlMap)) {
  const r1 = await sql`UPDATE public.flops SET link = ${newUrl} WHERE link = ${oldUrl} RETURNING id`
  const r2 = await sql`UPDATE public.talaref_entries SET link = ${newUrl} WHERE link = ${oldUrl} RETURNING id`
  const r3 = await sql`UPDATE public.talaref_entries SET thumbnail = ${newUrl} WHERE thumbnail = ${oldUrl} RETURNING id`
  const n = r1.length + r2.length + r3.length
  if (n > 0) {
    totalRows += n
    console.log(`  ✓ ${oldUrl.slice(0, 80)}... → ${n} row(s)`)
  }
}

console.log(`\nTotal row updates: ${totalRows}`)

console.log('\n--- Verifying ---')
const leftover = await sql`
  SELECT 'flops.link' as col, id::text FROM public.flops WHERE link LIKE '%supabase.co%'
  UNION ALL
  SELECT 'talaref.link', id::text FROM public.talaref_entries WHERE link LIKE '%supabase.co%'
  UNION ALL
  SELECT 'talaref.thumbnail', id::text FROM public.talaref_entries WHERE thumbnail LIKE '%supabase.co%'
`
if (leftover.length) {
  console.warn('⚠️ Still pointing at supabase.co:', leftover)
} else {
  console.log('✅ All Supabase URLs replaced.')
}
